FROM public.ecr.aws/lambda/python:3.11

# Install cosign
RUN curl -sL "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64" -o /usr/local/bin/cosign && \
    chmod +x /usr/local/bin/cosign

# Copy function code
COPY signer.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler
CMD [ "signer.handler" ]
